porting this plugin base on sf version
EC-CUBE/maker-plugin pull request #28
Opened 2018-05-18 11:27 UTC by hoand-vn

## 概要(Overview・Refs Issue)
+ Refactor plugin base on sf version

## 方針(Policy)
+ このPullRequestを作るにあたって考慮したものや除外した内容
   - none 
## 実装に関する補足(Appendix)
  - not using del_flag in DB

2018-07-10 11:19 UTC, ryo-endo requested changes

2018-07-10 11:19 UTC, ryo-endo commented on Resource/template/admin/maker.twig
> +{% extends '@admin/styleguide_frame.twig' %}
use '@admin/default_frame.twig'

2018-07-10 11:20 UTC, ryo-endo requested changes
navi.php
'admin.plugin.maker.sub_title'
↓
'admin.plugin.maker.title',

2018-07-12 02:59 UTC, hoand-vn commented
close for fixing

2018-07-12 03:24 UTC, hoand-vn commented
finish fixing

2018-08-13 05:02 UTC, ryo-endo commented
#29 でみなさんのコミット含めて取り込みましたのでCLOSEします。

2018-08-13 05:02 UTC, closed without merging